---
- name: Converge
  hosts: all
  vars:
    database_password: "1234"
    database_root_password: "5678"
    database_backup_user_password: "5432"
  tasks:
    - name: Include opencast_mariadb
      ansible.builtin.include_role:
        name: elan.opencast_mariadb
